import { useTheme } from '../contexts/ThemeContext'
import { Link } from 'react-router-dom'

export default function Terms() {
  const { theme, toggleTheme } = useTheme()

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-300 font-sans transition-colors duration-300 py-12 px-6">
      <div className="max-w-3xl mx-auto bg-white dark:bg-slate-900/50 p-8 md:p-12 rounded-3xl shadow-sm border border-slate-200 dark:border-white/10 relative overflow-hidden">
        
        <div className="absolute top-0 right-0 p-6">
          <Link to="/" className="text-sm font-bold text-cyan-600 dark:text-cyan-400 hover:underline">← Back to Home</Link>
        </div>

        <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 dark:text-white mb-8 tracking-tight">Terms & Conditions</h1>
        
        <div className="space-y-8 text-sm md:text-base leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account and using SmartSpend AI ("the App"), you agree to abide by these Terms and Conditions. If you do not agree, please do not use the service.</p>
          </section>
          
          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">2. Not Financial Advice</h2>
            <p>SmartSpend AI is an expense tracking and analytics tool designed for informational purposes only. The insights and budgets generated by the App do not constitute professional financial, investment, or legal advice. You are solely responsible for your financial decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">3. User Responsibilities</h2>
            <p>You are responsible for maintaining the confidentiality of your login credentials. You are also responsible for the accuracy of the financial data you input or log using the AI. We are not liable for any losses resulting from inaccurate data entry or unauthorized account access.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">4. Service Availability</h2>
            <p>We strive to keep the App online and accessible, but we do not guarantee 100% uptime. The service is provided on an "as is" and "as available" basis. We may pause or suspend the service temporarily for maintenance or updates without prior notice.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">5. Data Deletion and Termination</h2>
            <p>You reserve the right to export your data or permanently delete your account at any time through the Profile settings. We reserve the right to suspend or terminate your account if you attempt to abuse the system, hack the service, or violate these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-3">6. Changes to Terms</h2>
            <p>We may update these terms occasionally. Your continued use of the App following any changes indicates your acceptance of the new terms.</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-200 dark:border-white/10 text-center text-sm text-slate-500">
          Last updated: August 2026
        </div>
      </div>
    </div>
  )
}
